export const cities = [
    "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Amasya", "Ankara", "Antalya", "Artvin", "Aydın", "Balıkesir", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkari", "Hatay", "Isparta", "Mersin", "İstanbul", "İzmir", "Kars", "Kastamonu", "Kayseri", "Kırklareli", "Kırşehir", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Kahramanmaraş", "Mardin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Şanlıurfa", "Uşak", "Van", "Yozgat", "Zonguldak", "Aksaray", "Bayburt", "Karaman", "Kırıkkale", "Batman", "Şırnak", "Bartın", "Ardahan", "Iğdır", "Yalova", "Karabük", "Kilis", "Osmaniye", "Düzce"
];

export const cityDistricts = {
    "Adana": ["Seyhan", "Çukurova", "Yüreğir", "Sarıçam", "Ceyhan", "Kozan"],
    "Adıyaman": ["Merkez", "Kahta", "Besni", "Gölbaşı"],
    "Afyonkarahisar": ["Merkez", "Sandıklı", "Dinar", "Bolvadin"],
    "Ağrı": ["Merkez", "Patnos", "Doğubayazıt", "Diyadin"],
    "Amasya": ["Merkez", "Merzifon", "Suluova", "Gümüşhacıköy"],
    "Ankara": ["Çankaya", "Keçiören", "Yenimahalle", "Mamak", "Etimesgut", "Sincan", "Altındağ", "Gölbaşı", "Pursaklar", "Polatlı"],
    "Antalya": ["Muratpaşa", "Kepez", "Konyaaltı", "Alanya", "Manavgat", "Serik", "Döşemealtı", "Kumluca"],
    "Artvin": ["Merkez", "Hopa", "Arhavi", "Borçka"],
    "Aydın": ["Efeler", "Nazilli", "Söke", "Kuşadası", "Didim", "İncirliova"],
    "Balıkesir": ["Karesi", "Altıeylül", "Bandırma", "Edremit", "Gönen", "Ayvalık"],
    "Bilecik": ["Merkez", "Bozüyük", "Osmaneli"],
    "Bingöl": ["Merkez", "Genç", "Solhan"],
    "Bitlis": ["Merkez", "Tatvan", "Ahlat", "Güroymak"],
    "Bolu": ["Merkez", "Gerede", "Mudurnu"],
    "Burdur": ["Merkez", "Bucak", "Gölhisar"],
    "Bursa": ["Nilüfer", "Osmangazi", "Yıldırım", "Mudanya", "Gürsu", "Kestel", "İnegöl", "Gemlik", "Mustafakemalpaşa"],
    "Çanakkale": ["Merkez", "Biga", "Çan", "Gelibolu"],
    "Çankırı": ["Merkez", "Çerkeş", "Ilgaz"],
    "Çorum": ["Merkez", "Sungurlu", "Osmancık", "İskilip"],
    "Denizli": ["Pamukkale", "Merkezefendi", "Acıpayam", "Tavas"],
    "Diyarbakır": ["Bağlar", "Kayapınar", "Yenişehir", "Sur", "Ergani", "Bismil", "Silvan"],
    "Edirne": ["Merkez", "Keşan", "Uzunköprü"],
    "Elazığ": ["Merkez", "Kovancılar", "Karakoçan"],
    "Erzincan": ["Merkez", "Tercan", "Üzümlü"],
    "Erzurum": ["Yakutiye", "Palandöken", "Aziziye", "Oltu", "Horasan"],
    "Eskişehir": ["Odunpazarı", "Tepebaşı", "Sivrihisar"],
    "Gaziantep": ["Şahinbey", "Şehitkamil", "Nizip", "İslahiye"],
    "Giresun": ["Merkez", "Bulancak", "Espiye", "Görele"],
    "Gümüşhane": ["Merkez", "Kelkit", "Şiran"],
    "Hakkari": ["Merkez", "Yüksekova", "Şemdinli"],
    "Hatay": ["Antakya", "İskenderun", "Defne", "Samandağ", "Dörtyol", "Kırıkhan"],
    "Isparta": ["Merkez", "Eğirdir", "Yalvaç"],
    "Mersin": ["Yenişehir", "Mezitli", "Toroslar", "Akdeniz", "Tarsus", "Silifke", "Erdemli"],
    "İstanbul": ["Kadıköy", "Beşiktaş", "Üsküdar", "Şişli", "Fatih", "Beyoğlu", "Maltepe", "Kartal", "Pendik", "Sarıyer", "Ataşehir", "Bakırköy", "Bahçelievler", "Küçükçekmece", "Büyükçekmece", "Esenyurt", "Beylikdüzü", "Sancaktepe", "Çekmeköy", "Tuzla", "Ümraniye", "Gaziosmanpaşa", "Sultangazi", "Eyüpsultan"],
    "İzmir": ["Konak", "Karşıyaka", "Bornova", "Buca", "Çiğli", "Gaziemir", "Balçova", "Narlıdere", "Karabağlar", "Bayraklı", "Menemen", "Torbalı", "Ödemiş", "Bergama"],
    "Kars": ["Merkez", "Kağızman", "Sarıkamış"],
    "Kastamonu": ["Merkez", "Tosya", "İnebolu"],
    "Kayseri": ["Melikgazi", "Kocasinan", "Talas", "Develi"],
    "Kırklareli": ["Merkez", "Lüleburgaz", "Babaeski"],
    "Kırşehir": ["Merkez", "Kaman", "Mucur"],
    "Kocaeli": ["İzmit", "Gebze", "Darıca", "Körfez", "Gölcük", "Derince", "Çayırova", "Kartepe", "Başiskele"],
    "Konya": ["Selçuklu", "Meram", "Karatay", "Ereğli", "Akşehir", "Beyşehir"],
    "Kütahya": ["Merkez", "Tavşanlı", "Simav", "Gediz"],
    "Malatya": ["Yeşilyurt", "Battalgazi", "Doğanşehir"],
    "Manisa": ["Yunusemre", "Şehzadeler", "Akhisar", "Turgutlu", "Salihli", "Soma"],
    "Kahramanmaraş": ["Onikişubat", "Dulkadiroğlu", "Elbistan", "Afşin"],
    "Mardin": ["Artuklu", "Kızıltepe", "Midyat", "Nusaybin"],
    "Muğla": ["Menteşe", "Bodrum", "Fethiye", "Milas", "Marmaris", "Dalaman", "Ortaca"],
    "Muş": ["Merkez", "Bulanık", "Malazgirt"],
    "Nevşehir": ["Merkez", "Ürgüp", "Avanos"],
    "Niğde": ["Merkez", "Bor", "Çiftlik"],
    "Ordu": ["Altınordu", "Ünye", "Fatsa"],
    "Rize": ["Merkez", "Çayeli", "Ardeşen", "Pazar"],
    "Sakarya": ["Adapazarı", "Serdivan", "Erenler", "Hendek", "Akyazı", "Karasu"],
    "Samsun": ["Atakum", "İlkadım", "Canik", "Bafra", "Çarşamba", "Tekkeköy"],
    "Siirt": ["Merkez", "Kurtalan"],
    "Sinop": ["Merkez", "Boyabat", "Gerze"],
    "Sivas": ["Merkez", "Şarkışla", "Yıldızeli"],
    "Tekirdağ": ["Süleymanpaşa", "Çorlu", "Çerkezköy", "Kapaklı", "Ergene"],
    "Tokat": ["Merkez", "Erbaa", "Turhal", "Niksar"],
    "Trabzon": ["Ortahisar", "Akçaabat", "Araklı", "Of", "Yomra"],
    "Tunceli": ["Merkez", "Pertek"],
    "Şanlıurfa": ["Haliliye", "Eyyübiye", "Karaköprü", "Siverek", "Viranşehir", "Suruç"],
    "Uşak": ["Merkez", "Banaz", "Eşme"],
    "Van": ["İpekyolu", "Tuşba", "Edremit", "Erciş"],
    "Yozgat": ["Merkez", "Sorgun", "Akdağmadeni"],
    "Zonguldak": ["Merkez", "Ereğli", "Çaycuma", "Kozlu"],
    "Aksaray": ["Merkez", "Eskil"],
    "Bayburt": ["Merkez"],
    "Karaman": ["Merkez", "Ermenek"],
    "Kırıkkale": ["Merkez", "Yahşihan"],
    "Batman": ["Merkez", "Kozluk"],
    "Şırnak": ["Merkez", "Cizre", "Silopi"],
    "Bartın": ["Merkez"],
    "Ardahan": ["Merkez"],
    "Iğdır": ["Merkez"],
    "Yalova": ["Merkez", "Çınarcık"],
    "Karabük": ["Merkez", "Safranbolu"],
    "Kilis": ["Merkez"],
    "Osmaniye": ["Merkez", "Kadirli"],
    "Düzce": ["Merkez", "Akçakoca"]
};
